# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

sum = 0
n = 1
n_minus = 1

while (n <= 4000000):
	if (n%2==0):
		sum += n
	n_plus = n + n_minus
	n_minus = n
	n = n_plus

print sum
